### ISSUE TITLE
Warn if a package is on the checkouts of multiple plone versions

### ISSUE THREAD

**Issue by gforcada** [plone/plone.releaser#12]
When releasing with zest.releaser and plone.releaser the buildout.coredev branch one is on gets updated with the new version pin and an entry removed on checkouts.cfg.

Still that very same checkout is maybe on another branch (say plone.app.contenttypes is released while on buildout.coredev branch 5.1 and is also on checkouts on buildout.coredev branch 5.0).

plone.releaser should check with mr.roboto (JSON http://jenkins.plone.org/roboto/checkouts.json) if there is any other buildout.coredev version that also has on its checkouts.cfg the same package being released targeting the same branch, so that it can be updated manually as well.

**Comment by gforcada** [comment]
Without involving mr.roboto this is implemented by #14

**Comment by mauritsvanrees** [comment]
I think this can be closed. The PR was merged.
