### ISSUE TITLE
update other buildout.coredev branches does not work in some cases

### ISSUE THREAD

**Issue by gforcada** [plone/plone.releaser#20]
Say you release ( as I did) plone.testing that is checked out on 5.0 and 5.1 while being on 5.2. No commits will be done on those two branches on buildout.coredev.

Instead, if I'm on buildout.coredev 5.1 both 5.1 and 5.0 will be updated.

**Comment by mauritsvanrees** [comment]
This is working fine for me. At least I haven't noticed problems.
Currently 5.0, 5.1 and 5.2 are each using a different branch of plone.testing, so currently it shouldn't update any other branches, but that will have been different when you posted this issue.

Are your checkouts of 5.1 and 5.0 up to date on your 5.2 checkout?

I have four directories (named simply 4.3 to 5.2) with a checkout of the coredev branch of the same name. I have a script that updates all those checkouts, *including* the other branches in this checkout:

```
cat ~/bin/update-plone-coredev.sh 
#!/bin/sh
BASEDIR=~/community/plone-coredev
for checkout in 4.3 5.0 5.1 5.2; do
    echo
    echo "====================="
    cd $BASEDIR/$checkout
    pwd
    git fetch
    for branch in 4.3 5.0 5.1 5.2; do
        git checkout $branch
        git merge --ff-only
    done
    # Go back to original branch
    git checkout $checkout
done
```

**Comment by mauritsvanrees** [comment]
I will close this.  No comment since a year, and I have not seen this myself.

I have meanwhile updated by script from above, to handle the new 6.0 branch and a bit more:

```
#!/bin/sh
BASEDIR=~/community/plone-coredev
for checkout in 4.3 5.0 5.1 5.2 py3 6.0; do
    echo
    echo "====================="
    cd $BASEDIR/$checkout
    pwd
    git fetch
    for branch in 4.3 5.0 5.1 5.2 6.0; do
        git checkout $branch
        git merge --ff-only
    done
    # Go back to original branch
    if test $checkout == "py3"; then
        checkout="5.2"
    fi
    git checkout $checkout
done

full=0
fresh=0
if test "x$1" == "x--full"; then
    echo "Will run full buildout."
    full=1
elif test "x$1" == "x--fresh"; then
    echo "Will run fresh buildout."
    fresh=1
else
    echo "Done. Not running buildout. Call with --full or --fresh if you want."
    exit 0
fi
# Run the extra command for all, except for 5.0.
for checkout in 4.3 5.1 5.2 py3 6.0; do
    echo
    echo "====================="
    cd $BASEDIR/$checkout
    pwd
    if test $fresh; then
        if test "$checkout" == "py3" -o "$checkout" == "6.0"; then
            venv3.sh
        else
            venv27buildout.sh
        fi
    fi
    bin/buildout
done
```
