### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.releaser#3]
Could a new release be made?

I'm working on [freitag.releaser](https://github.com/derFreitag/freitag.releaser) and Travis fails on py3 jobs due to old syntax formatting that is already fixed in git but not released.

And yes, I will push any changes that could be part of zest.releaser or plone.releaser :-)

**Comment by tisto** [comment]
Done. Do you want me to grant you release permissions on pypi?

**Comment by gforcada** [comment]
Well actually I still have to send my credentials so I can do plone releases as well (being part of the release team). So I wanted to use that as my testing release :-)
