### ISSUE TITLE
buildout.coredev dependency version pins

### ISSUE THREAD

**Issue by jensens** [plone/plone.releaser#38]
This package uses ``gitpython``. buildout.coredev pins a completly outdated version (inlcuding its outdated dependencies ``gitpython2`` and ``gitdb`` - maybe more).

Is this by intend or accident?

**Comment by mauritsvanrees** [comment]
The thought was: "If it ain't broken, don't fix it." It works with this version, package releases are going fine.
You were the last one to update this pin, in February.
It is probably fine to upgrade to newer versions. If they don't work in practice next time I do some releases, I can always revert an update.

**Comment by jensens** [comment]
Same thought here, I only updated on minor and bugfix level IIRC. Well, lets try it. I like to have new version around.
