### ISSUE TITLE
Update unified changelog generation to include feature/bug tags

### ISSUE THREAD

**Issue by esteele** [plone/plone.releaser#4]
Current script strips those designations.

**Comment by mauritsvanrees** [comment]
I fixed this a few days after you reported this, and I did not even look at the issue tracker. :-)

See 036fc5873c2821ffb514bc2f4181aa7b79ca8182 plus afterwards.

Please also check this coredev commit of a minute ago where I have updated the release docs:
https://github.com/plone/buildout.coredev/commit/6f056e29382ceab1206c9b4d3296a630205416cf

**Comment by gforcada** [comment]
@mauritsvanrees any reason then to keep this ticket open then?
